FROM node:20-alpine

WORKDIR /app/frontend

COPY packages /app/packages
COPY frontend/package.json frontend/package-lock.json ./

RUN npm install

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD npm install && npm run dev
