export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/dashboard/index',
    'pages/wardrobe/index',
    'pages/suggest/index',
    'pages/pairings/index',
    'pages/outfits/index',
    'pages/history/index',
    'pages/analytics/index',
    'pages/learning/index',
    'pages/family/index',
    'pages/family-feed/index',
    'pages/notifications/index',
    'pages/settings/index',
    'pages/onboarding/index',
    'pages/invite/index',
  ],
  tabBar: {
    color: '#6B7280',
    selectedColor: '#0F172A',
    backgroundColor: '#FFFFFF',
    borderStyle: 'black',
    list: [
      { pagePath: 'pages/dashboard/index', text: '首页' },
      { pagePath: 'pages/wardrobe/index', text: '衣橱' },
      { pagePath: 'pages/suggest/index', text: '推荐' },
      { pagePath: 'pages/outfits/index', text: '穿搭' },
    ],
  },
  window: {
    navigationBarTitleText: 'Wardrowbe',
    navigationStyle: 'default',
  },
})
