export default {
  pages: [
    "pages/login/index",
    "pages/dashboard/index",
    "pages/wardrobe/index",
    "pages/suggest/index",
    "pages/pairings/index",
    "pages/outfits/index",
    "pages/history/index",
    "pages/analytics/index",
    "pages/learning/index",
    "pages/family/index",
    "pages/notifications/index",
    "pages/settings/index",
    "pages/onboarding/index",
    "pages/invite/index",
    "pages/family-feed/index",
    "pages/outfit-detail/index",
    "pages/outfit-new/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#1a1a1a",
    navigationBarTitleText: "Wardrowbe",
    navigationBarTextStyle: "white",
  },
  tabBar: {
    color: "#888888",
    selectedColor: "#e8b4a0",
    backgroundColor: "#1a1a1a",
    borderStyle: "black",
    list: [
      {
        pagePath: "pages/dashboard/index",
        text: "首页",
        iconPath: "assets/tab/home.png",
        selectedIconPath: "assets/tab/home-active.png",
      },
      {
        pagePath: "pages/wardrobe/index",
        text: "衣橱",
        iconPath: "assets/tab/wardrobe.png",
        selectedIconPath: "assets/tab/wardrobe-active.png",
      },
      {
        pagePath: "pages/suggest/index",
        text: "推荐",
        iconPath: "assets/tab/suggest.png",
        selectedIconPath: "assets/tab/suggest-active.png",
      },
      {
        pagePath: "pages/pairings/index",
        text: "搭配",
        iconPath: "assets/tab/pairings.png",
        selectedIconPath: "assets/tab/pairings-active.png",
      },
      {
        pagePath: "pages/outfits/index",
        text: "穿搭",
        iconPath: "assets/tab/outfits.png",
        selectedIconPath: "assets/tab/outfits-active.png",
      },
    ],
  },
};
